services:
  keycash-database:
    image: mysql
    container_name: keycash-database
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=real_estate_db
    networks:
      - db_api-net
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - db_api-net

  api:
    build: .
    container_name: real-estate-api
    entrypoint: dockerize -wait tcp://keycash-database:3306 -timeout 30s npm run dev
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    networks:
      - db_api-net

volumes:
  mysqldata:

networks:
  db_api-net:
    driver: bridge